### ISSUE TITLE
Use attr_accessor for `properties` on TelemetryContext

### ISSUE THREAD

**Issue by emancu** [Microsoft/AppInsights-Ruby#3]
All the attributes have a _getter_ and a _setter_ except `properties`.
It would be nice to accept an entire hash for this property.

https://github.com/Microsoft/AppInsights-Ruby/blob/master/lib/application_insights/channel/telemetry_context.rb#L63-L65

**Comment by jngli** [comment]
Sure, thanks!

**Comment by emancu** [comment]
@jngli and also it would be great to set the `context` for a TelemetryClient.

BTW is there any IRC channel or place to ask about the usage of this gem?
I've some questions to ask.

**Comment by jngli** [comment]
You can set context via the context property on TelemetryClient, e.g.,
tc = ApplicationInsights::TelemetryClient.new
tc.context.application.ver = '2.0'

Please check the documentation for common usage: http://microsoft.github.io/AppInsights-Ruby/.  If you have further questions, please use AI forum https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights

Thanks!

**Comment by emancu** [comment]
@jngli The thing is I want to keep a hash with all the configs and do a massive assignment to the context.

Given the context doesn't support a massive assignment, I thought that I can create and configure a `Context` and then update it for every telemetry Client.
Maybe I should open a new issue or submit some PRs with different approaches.

**Comment by jngli** [comment]
I've submitted the properties setter change. Also, a new gem version is released with request auto collection.

For the context massive assignment, feel free to open a new issue or submit a PR if you think this would be a common issue.
