### ISSUE TITLE
Bug: OpenSSL Error for `tc.flush`

### ISSUE THREAD

**Issue by dkullmann** [Microsoft/AppInsights-Ruby#4]
When attempting to execute the [sample code in the README](https://github.com/Microsoft/AppInsights-Ruby#sending-a-simple-event-telemetry-item) I run into an OpenSSL error (copied below.) I noticed that this only occurred when `tc.flush` was called.

Upon further investigation I found that the `openssl` library wasn't required in the [`sender_base.rb`](https://github.com/Microsoft/AppInsights-Ruby/blob/master/lib/application_insights/channel/sender_base.rb#L1-L4) file. adding `require 'openssl'` resolved the issue for me.

```
/Users/dkullmann/.rvm/gems/ruby-2.1.3/gems/application_insights-0.5.0/lib/application_insights/channel/sender_base.rb:54:in `send': uninitialized constant ApplicationInsights::Channel::SenderBase::OpenSSL (NameError)
	from /Users/dkullmann/.rvm/gems/ruby-2.1.3/gems/application_insights-0.5.0/lib/application_insights/channel/synchronous_queue.rb:34:in `flush'
	from /Users/dkullmann/.rvm/gems/ruby-2.1.3/gems/application_insights-0.5.0/lib/application_insights/channel/telemetry_channel.rb:47:in `flush'
	from /Users/dkullmann/.rvm/gems/ruby-2.1.3/gems/application_insights-0.5.0/lib/application_insights/telemetry_client.rb:214:in `flush'
	from test.rb:4:in `<main>'
```

Here is a link to [line 54](https://github.com/Microsoft/AppInsights-Ruby/blob/master/lib/application_insights/channel/sender_base.rb#L54) where the error is from.

**Comment by jngli** [comment]
What is the ruby version you are using?

**Comment by dkullmann** [comment]
@jngli the gem version + ruby version are in the error path: `ruby-2.1.3` and `application_insights-0.5.0`

I can try with alternate versions if you need me to (I saw your README said it only supports 1.9.3)

**Comment by dkullmann** [comment]
@jngli btw, thanks for such a fast reply!

**Comment by jngli** [comment]
The develop version we are currently using is 1.9.3, however I expect it works with higher stable version as well, if not, we'd like to fix it.

For 1.9.3, 'openssl' is not required as net/http auto loads it.  I checked latest 2.2 which does the same thing. Could you please check 2.1.3?

**Comment by dkullmann** [comment]
@jngli yeah, I'll investigate further and see if I can provide more information.

**Comment by dkullmann** [comment]
The 2.2.0 docs say ["in previous versions you had to require net/https to use https"](http://ruby-doc.org/stdlib-2.2.0/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-HTTPS) — but it appears that was added on [January 8th, 2010](https://github.com/ruby/ruby/commit/e0cdab5fff0e57bdea2cb3237e5031dd69fbada5#diff-8c2ab8e0fb4f052e1d95ab6334e192c1) so I it's probably there in 2.1/1.9/etc =)

ruby [autoloads OpenSSL](https://github.com/ruby/ruby/blob/1711e80cf16799ee84a75b0089807937e39fdbfe/lib/net/http.rb#L26) in Net::HTTP. However, in `application_insights` gem code _I think we reference OpenSSL before Net::HTTP does, and therefore it is not autoloaded yet._

To test this I tried calling the Net::HTTP methods which reference OpenSSL (creating an SSL request, making the autoload work) and then the appinsights gem — this fixed the problem:

**This works**
```
require 'application_insights'

uri = URI('https://citrusbyte.com')

Net::HTTP.start(uri.host, uri.port,
  :use_ssl => uri.scheme == 'https') do |http|
  request = Net::HTTP::Get.new uri
  response = http.request request # Net::HTTPResponse object
end

tc = ApplicationInsights::TelemetryClient.new 'c28ef852-fbee-460c-9a87-0e6e58ea07b9'
tc.track_event 'My event'
tc.flush
```

**This doesn't**
```
require 'application_insights'
tc = ApplicationInsights::TelemetryClient.new 'c28ef852-fbee-460c-9a87-0e6e58ea07b9'
tc.track_event 'My event'
tc.flush
```

I also made this test:
```
require 'net/http'
OpenSSL::SSL::VERIFY_NONE
```
Which gives the same error — and similarly is fixed if I add the Net::HTTP call beforehand with `use_ssl` which autoloads `openssl`

**Comment by dkullmann** [comment]
Note: This could still be my setup, or differences in how autoloading works for different ruby versions.

**Comment by jngli** [comment]
Thanks for taking time investigating!
It turns out it only auto loads inside the module Net since 2.0.0.0. Thus the following code works

module A
  autoload :OpenSSL, 'openssl'
  verify_mode = OpenSSL::SSL::VERIFY_NONE
end

While this one does not as OpenSSL is not accessed in the namespace of A
module A
  autoload :OpenSSL, 'openssl'
end
verify_mode = OpenSSL::SSL::VERIFY_NONE

I will update to require 'openssl' explicitly with a new release gem later.

**Comment by jngli** [comment]
@dkullmann the new gem is released

**Comment by dkullmann** [comment]
@jngli awesome, thank you!

**Comment by dkullmann** [comment]
@jngli confirmed fixed!
