### ISSUE TITLE
Version missmatch

### ISSUE THREAD

**Issue by emancu** [Microsoft/AppInsights-Ruby#5]
The version specified at `version.rb` file is `0.5.1` but I found a `0.1.0` version in the middle of the code.

https://github.com/citrusbyte/AppInsights-Ruby/blob/master/lib/application_insights/channel/telemetry_channel.rb#L80

Is it an issue?

**Comment by jngli** [comment]
Yes, I'll fix that.  Thanks!

**Comment by jngli** [comment]
This is fixed in 0.5.2
