### ISSUE TITLE
Release date for 0.5.7

### ISSUE THREAD

**Issue by peteryates** [Microsoft/AppInsights-Ruby#71]
We're using this gem and everything's going well but we'd like to use the `ApplicationInsights::Rack::InjectJavaScriptTracking` middleware, ideally without adding the Github repo to our gemfile.

Is there a scheduled release date for `0.5.7`?

**Comment by satoryu** [comment]
Is there any contributor/owner able to release? how about this @SergeyKanzhelev ?
