### ISSUE TITLE
Unable to set role_name and role_instance

### ISSUE THREAD

**Issue by Mexxiax** [Microsoft/AppInsights-Ruby#79]
Hi there,

Could someone explain me how to set role_name and role_instance?
I've set like this:
sender = ApplicationInsights::Channel::AsynchronousSender.new
queue = ApplicationInsights::Channel::AsynchronousQueue.new sender
channel = ApplicationInsights::Channel::TelemetryChannel.new nil, queue
tc = ApplicationInsights::TelemetryClient.new 'key', channel
tc.context.cloud.role_name = 'Sample Name'
tc.context.cloud.role_instance = 'Sample Instance'

But role_name and role_instance dont appear on Application Insights Dashboard > Application Map

**Comment by rodrigovirgilio** [comment]
How I solved this problem by rewriting the method `telemetry_context` in https://github.com/microsoft/ApplicationInsights-Ruby/blob/develop/lib/application_insights/rack/track_request.rb#L144:

`Gemfile`

```ruby
gem 'application_insights', git: 'https://github.com/microsoft/ApplicationInsights-Ruby', branch: 'develop'
```

`config/application.rb`

```ruby
require_relative '../lib/rack/track_request'

config.middleware.use 'ApplicationInsights::Rack::TrackRequest', '<YOUR INSTRUMENTATION KEY GOES HERE>'
```

`lib/rack/track_request.rb`

```ruby
require 'application_insights'

module ApplicationInsights
  module Rack
    # Track every request and sends the request data to Application Insights.
    class TrackRequest
      private

      def telemetry_context(request_id, request_id_header)
        context = Channel::TelemetryContext.new
        context.instrumentation_key = @instrumentation_key
        context.operation.id = operation_id(request_id)
        context.operation.parent_id = request_id_header
        context.cloud.role = 'app-role-name'
        context.cloud.role_instance = 'app-role-instance'

        context
      end
    end
  end
end
```

Note: I am preparing a PR to resolve this.
